version: '3.8'
services:
  db_mongo:
    container_name: db_mongo
    image: mongo:7.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test


