version: '3.8'
services:
  db_mongo:
    container_name: db_mongo
    image: mongo:7.0.3
    command: mongod --port 81
    ports:
      - '81:81'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: test


